alter table ALBUM_SONG drop constraint FKEC3CB90581B87C90;
alter table ALBUM_SONG drop constraint FKEC3CB905EB7309A4;
alter table ALL_DATA_TYPE_STRING_COLL drop constraint FKF282088C4BF51B40;
alter table ASSISTANT drop constraint FKFB5182BE85D03B3B;
alter table ASSISTANT_PROFESSOR drop constraint FK7FCA8E0E85D03B3B;
alter table ASSOCIATE_PROFESSOR drop constraint FKEBBADA4E85D03B3B;
alter table AUTHOR_BOOK drop constraint FKAC90951D11B08037;
alter table AUTHOR_BOOK drop constraint FKAC90951DC52E8EB7;
alter table BAG_HANDLE drop constraint FK8FC82A5FCEA84F85;
alter table BAG_HANDLE drop constraint FK8FC82A5FF35A2E0F;
alter table BRIDE_FATHER_IN_LAW drop constraint FKBF51C6660B31E4;
alter table BRIDE_FATHER_IN_LAW drop constraint FKBF51C66CCF145D9;
alter table BRIDE_MOTHER_IN_LAW drop constraint FKFD41551FCCF145D9;
alter table BRIDE_MOTHER_IN_LAW drop constraint FKFD41551F3160483;
alter table CARD drop constraint FK1F731031FBD7EF;
alter table CASH drop constraint FK1F7333C2A7FD6D;
alter table CHAIN_PENDANT drop constraint FKC8C94BDE7F591DB2;
alter table CHAIN_PENDANT drop constraint FKC8C94BDE8C56A5D2;
alter table CHEF drop constraint FK1F8BC698E6C48E;
alter table CHILD drop constraint FK3D1FCFCA78EABE9;
alter table CHILD drop constraint FK3D1FCFCEB5F2EB0;
alter table CREDIT drop constraint FK76F89EF9C2A7FD6D;
alter table CREDIT drop constraint FK76F89EF9689593A7;
alter table CRT_MONITOR drop constraint FKDEE160C0196EE11C;
alter table DESSERT_UTENSIL drop constraint FK4A0B93F5B3B2C9F5;
alter table DESSERT_UTENSIL drop constraint FK4A0B93F524333AC3;
alter table ELEMENT drop constraint FKC7AEAADCFE34B82A;
alter table EMPLOYEE_PROJECT drop constraint FKCE01C668422BA5BC;
alter table EMPLOYEE_PROJECT drop constraint FKCE01C668D110B418;
alter table FISH drop constraint FK20EE582F7DE34C;
alter table FISH drop constraint FK20EE58ADE8D522;
alter table FLIGHT_PASSANGER drop constraint FK36CAD672729AF81;
alter table FLIGHT_PASSANGER drop constraint FK36CAD67432BA4D3;
alter table GRADUATE_STUDENT drop constraint FKCDCC8727904FA5F6;
alter table GRAPHIC_CALCULATOR drop constraint FK5CA0E0D9380BE9AC;
alter table HAND_CARD drop constraint FKAAF560E0CA3044AF;
alter table HAND_CARD drop constraint FKAAF560E0C1E7350F;
alter table HARD_DRIVE drop constraint FK53512116252B1531;
alter table HUMAN drop constraint FK41E690D4AEB8790;
alter table LATCH_KEY drop constraint FK368069A481259D82;
alter table LCD_MONITOR drop constraint FK865718A8196EE11C;
alter table LUGGAGE drop constraint FK496F4C16485FE8B5;
alter table MONITOR drop constraint FK747C493A8E7C481C;
alter table PERSON drop constraint FK8C768F552E0F2091;
alter table PRIVATE_TEACHER drop constraint FK54CF9CE6406FC5A8;
alter table PRODUCT drop constraint FK185958CFD8F5D084;
alter table PUPIL drop constraint FK48F314E406FC5A8;
alter table SALTWATER_FISH_TANK_SUBSTRATE drop constraint FKF5625DB5A62A2163;
alter table SALTWATER_FISH_TANK_SUBSTRATE drop constraint FKF5625DB514F404D3;
alter table SHIRT_BUTTON drop constraint FKB28F85BBF7949550;
alter table SHIRT_BUTTON drop constraint FKB28F85BBD9B4EA64;
alter table SHOES drop constraint FK4B38AC85DD3FA8D;
alter table SUIT drop constraint FK27030DFCD1226F;
alter table TANK_TANK_ACCESSORY drop constraint FKD95079D22F7DE34C;
alter table TANK_TANK_ACCESSORY drop constraint FKD95079D2ADE8D522;
alter table TANK_TANK_ACCESSORY drop constraint FKD95079D27022CE1E;
alter table TENURED_PROFESSOR drop constraint FKBA5BFB0985D03B3B;
alter table UNDERGRADUATE_STUDENT drop constraint FK2E261DF904FA5F6;
drop table ADDRESS if exists;
drop table ALBUM if exists;
drop table ALBUM_SONG if exists;
drop table ALL_DATA_TYPE if exists;
drop table ALL_DATA_TYPE_STRING_COLL if exists;
drop table ASSISTANT if exists;
drop table ASSISTANT_PROFESSOR if exists;
drop table ASSOCIATE_PROFESSOR if exists;
drop table AUTHOR if exists;
drop table AUTHOR_BOOK if exists;
drop table BAG if exists;
drop table BAG_HANDLE if exists;
drop table BANK if exists;
drop table BOOK if exists;
drop table BRIDE if exists;
drop table BRIDE_FATHER_IN_LAW if exists;
drop table BRIDE_MOTHER_IN_LAW if exists;
drop table BUTTON if exists;
drop table CALCULATOR if exists;
drop table CARD if exists;
drop table CASH if exists;
drop table CHAIN if exists;
drop table CHAIN_PENDANT if exists;
drop table CHARACTER_KEY if exists;
drop table CHARACTER_PRIMITIVE_KEY if exists;
drop table CHEF if exists;
drop table CHILD if exists;
drop table COMPUTER if exists;
drop table CREDIT if exists;
drop table CRT_MONITOR if exists;
drop table CURRENCY if exists;
drop table DECK if exists;
drop table DESIGNER if exists;
drop table DESSERT if exists;
drop table DESSERT_UTENSIL if exists;
drop table DISPLAY if exists;
drop table DOG if exists;
drop table DOUBLE_KEY if exists;
drop table DOUBLE_PRIMITIVE_KEY if exists;
drop table ELEMENT if exists;
drop table EMPLOYEE if exists;
drop table EMPLOYEE_PROJECT if exists;
drop table FISH if exists;
drop table FLIGHT if exists;
drop table FLIGHT_PASSANGER if exists;
drop table FLOAT_KEY if exists;
drop table FLOAT_PRIMITIVE_KEY if exists;
drop table FRESHWATER_FISH_TANK if exists;
drop table GOVERMENT if exists;
drop table GRADUATE_STUDENT if exists;
drop table GRAPHIC_CALCULATOR if exists;
drop table HAND if exists;
drop table HANDLE if exists;
drop table HAND_CARD if exists;
drop table HARD_DRIVE if exists;
drop table HUMAN if exists;
drop table INTEGER_KEY if exists;
drop table INTEGER_PRIMITIVE_KEY if exists;
drop table IN_LAW if exists;
drop table KEYCHAIN if exists;
drop table LATCH_KEY if exists;
drop table LCD_MONITOR if exists;
drop table LONG_KEY if exists;
drop table LONG_PRIMITIVE_KEY if exists;
drop table LUGGAGE if exists;
drop table MAMMAL if exists;
drop table MONITOR if exists;
drop table NO_ID_KEY if exists;
drop table ORDERLINE if exists;
drop table ORGANIZATION if exists;
drop table PARENT if exists;
drop table PASSANGER if exists;
drop table PAYMENT if exists;
drop table PENDANT if exists;
drop table PERSON if exists;
drop table PRIVATE_TEACHER if exists;
drop table PRODUCT if exists;
drop table PROFESSOR if exists;
drop table PROJECT if exists;
drop table PUPIL if exists;
drop table RESTAURANT if exists;
drop table SALTWATER_FISH_TANK if exists;
drop table SALTWATER_FISH_TANK_SUBSTRATE if exists;
drop table SHIRT if exists;
drop table SHIRT_BUTTON if exists;
drop table SHOES if exists;
drop table SONG if exists;
drop table STRING_KEY if exists;
drop table STRING_PRIMITIVE_KEY if exists;
drop table STUDENT if exists;
drop table SUBSTRATE if exists;
drop table SUIT if exists;
drop table TANK_ACCESSORY if exists;
drop table TANK_TANK_ACCESSORY if exists;
drop table TEACHER if exists;
drop table TENURED_PROFESSOR if exists;
drop table UNDERGRADUATE_STUDENT if exists;
drop table UTENSIL if exists;
drop table WHEEL if exists;
drop table hi_value if exists;
create table ADDRESS (ID integer not null, ZIP varchar(255), primary key (ID));
create table ALBUM (ID integer not null, TITLE varchar(255), primary key (ID));
create table ALBUM_SONG (SONG_ID integer not null, ALBUM_ID integer, primary key (SONG_ID));
create table ALL_DATA_TYPE (ID integer not null, BOOLEAN_PRIMITIVE_VALUE bit, BOOLEAN_VALUE bit, CHARACTER_PRIMITIVE_VALUE char(1), CHARACTER_VALUE char(1), CLOB_VALUE char(1), DATE_PRIMITIVE_VALUE timestamp, DATE_VALUE timestamp, DOUBLE_PRIMITIVE_VALUE double, DOUBLE_VALUE double, FLOAT_PRIMITIVE_VALUE float, FLOAT_VALUE float, INT_PRIMITIVE_VALUE integer, INT_VALUE integer, LONG_PRIMITIVE_VALUE bigint, LONG_VALUE bigint, STRING_PRIMITIVE_VALUE varchar(255), STRING_VALUE varchar(255), primary key (ID));
create table ALL_DATA_TYPE_STRING_COLL (ALL_DATA_TYPE_ID integer not null, STRING_VALUE varchar(255));
create table ASSISTANT (ID integer not null, NAME varchar(255), PROFESSOR_ID integer, primary key (ID));
create table ASSISTANT_PROFESSOR (PROFESSOR_ID integer not null, JOINING_YEAR integer, primary key (PROFESSOR_ID));
create table ASSOCIATE_PROFESSOR (PROFESSOR_ID integer not null, YEARS_SERVED integer, primary key (PROFESSOR_ID));
create table AUTHOR (ID integer not null, NAME varchar(255), primary key (ID));
create table AUTHOR_BOOK (BOOK_ID integer not null, AUTHOR_ID integer not null, primary key (BOOK_ID, AUTHOR_ID));
create table BAG (ID integer not null, STYLE varchar(255), primary key (ID));
create table BAG_HANDLE (BAG_ID integer not null, HANDLE_ID integer, primary key (BAG_ID), unique (HANDLE_ID));
create table BANK (ID integer not null, NAME varchar(255), primary key (ID));
create table BOOK (ID integer not null, NAME varchar(255), primary key (ID));
create table BRIDE (ID integer not null, NAME varchar(255), primary key (ID));
create table BRIDE_FATHER_IN_LAW (BRIDE_ID integer not null, IN_LAW_ID integer, primary key (BRIDE_ID), unique (IN_LAW_ID));
create table BRIDE_MOTHER_IN_LAW (BRIDE_D integer not null, IN_LAW_ID integer, primary key (BRIDE_D), unique (IN_LAW_ID));
create table BUTTON (ID integer not null, HOLES integer, primary key (ID));
create table CALCULATOR (ID integer not null, DISCRIMINATOR varchar(255) not null, BRAND varchar(255), primary key (ID));
create table CARD (ID integer not null, IMAGE char(1), NAME varchar(255), SUIT_ID integer not null, primary key (ID));
create table CASH (PAYMENT_ID integer not null, primary key (PAYMENT_ID));
create table CHAIN (ID integer not null, METAL varchar(255), primary key (ID));
create table CHAIN_PENDANT (CHAIN_ID integer not null, PENDANT_ID integer, primary key (PENDANT_ID), unique (PENDANT_ID));
create table CHARACTER_KEY (ID char(1) not null, NAME varchar(255), primary key (ID));
create table CHARACTER_PRIMITIVE_KEY (ID char(1) not null, NAME varchar(255), primary key (ID));
create table CHEF (ID integer not null, NAME varchar(255), RESTAURANT_ID integer not null, primary key (ID));
create table CHILD (ID integer not null, NAME varchar(255), MOTHER_ID integer, FATHER_ID integer, primary key (ID), unique (FATHER_ID), unique (MOTHER_ID));
create table COMPUTER (ID integer not null, TYPE varchar(255), primary key (ID));
create table CREDIT (PAYMENT_ID integer not null, CARD_NUMBER varchar(255), BANK_ID integer not null, primary key (PAYMENT_ID));
create table CRT_MONITOR (MONITOR_ID integer not null, REFRESH_RATE integer, primary key (MONITOR_ID));
create table CURRENCY (ID integer not null, DISCRIMINATOR varchar(255) not null, COUNTRY varchar(255), VALUE integer, primary key (ID));
create table DECK (ID integer not null, NAME varchar(255), primary key (ID));
create table DESIGNER (ID integer not null, NAME varchar(255), primary key (ID));
create table DESSERT (ID integer not null, DISCRIMINATOR varchar(255) not null, FILLING varchar(255), TOPPING varchar(255), primary key (ID));
create table DESSERT_UTENSIL (DESSERT_ID integer not null, UTENSIL_ID integer not null, primary key (UTENSIL_ID, DESSERT_ID));
create table DISPLAY (ID integer not null, HEIGHT integer, WIDTH integer, primary key (ID));
create table DOG (ID integer not null, BREED varchar(255), GENDER varchar(255), primary key (ID));
create table DOUBLE_KEY (ID double not null, NAME varchar(255), primary key (ID));
create table DOUBLE_PRIMITIVE_KEY (ID double not null, NAME varchar(255), primary key (ID));
create table ELEMENT (ID integer not null, NAME varchar(255), PARENT_ELEMENT_ID integer, primary key (ID));
create table EMPLOYEE (ID integer not null, NAME varchar(255), primary key (ID));
create table EMPLOYEE_PROJECT (EMPLOYEE_ID integer not null, PROJECT_ID integer not null, primary key (EMPLOYEE_ID, PROJECT_ID));
create table FISH (ID integer not null, DISCRIMINATOR varchar(255) not null, GENERA varchar(255), TANK_DISCRIMINATOR varchar(255), TANK_ID integer, PRIMARY_COLOR varchar(255), FIN_SIZE integer, primary key (ID));
create table FLIGHT (ID integer not null, DESTINATION varchar(255), primary key (ID));
create table FLIGHT_PASSANGER (PASSANGER_ID integer not null, FLIGHT_ID integer, primary key (PASSANGER_ID));
create table FLOAT_KEY (ID float not null, NAME varchar(255), primary key (ID));
create table FLOAT_PRIMITIVE_KEY (ID float not null, NAME varchar(255), primary key (ID));
create table FRESHWATER_FISH_TANK (ID integer not null, FILTER_MODEL varchar(255), NUM_GALLONS integer, SHAPE varchar(255), primary key (ID));
create table GOVERMENT (ID integer not null, DISCRIMINATOR varchar(255) not null, COUNTRY varchar(255), PRIME_MINISTER varchar(255), PRESIDENT varchar(255), primary key (ID));
create table GRADUATE_STUDENT (STUDENT_ID integer not null, PROJECT_NAME varchar(255), primary key (STUDENT_ID));
create table GRAPHIC_CALCULATOR (CALCULATOR_ID integer not null, primary key (CALCULATOR_ID));
create table HAND (ID integer not null, primary key (ID));
create table HANDLE (ID integer not null, COLOR varchar(255), primary key (ID));
create table HAND_CARD (HAND_ID integer not null, CARD_ID integer not null);
create table HARD_DRIVE (ID integer not null, DRIVE_SIZE integer, COMPUTER_ID integer not null, primary key (ID));
create table HUMAN (MAMMAL_ID integer not null, DIET varchar(255), primary key (MAMMAL_ID));
create table INTEGER_KEY (ID integer not null, NAME varchar(255), primary key (ID));
create table INTEGER_PRIMITIVE_KEY (ID integer not null, NAME varchar(255), primary key (ID));
create table IN_LAW (ID integer not null, NAME varchar(255), primary key (ID));
create table KEYCHAIN (ID integer not null, NAME varchar(255), primary key (ID));
create table LATCH_KEY (ID integer not null, TYPE varchar(255), KEYCHAIN_ID integer, primary key (ID));
create table LCD_MONITOR (MONITOR_ID integer not null, DPI_SUPPORTED integer, primary key (MONITOR_ID));
create table LONG_KEY (ID bigint not null, NAME varchar(255), primary key (ID));
create table LONG_PRIMITIVE_KEY (ID bigint not null, NAME varchar(255), primary key (ID));
create table LUGGAGE (ID integer not null, DISCRIMINATOR varchar(255) not null, CAPACITY integer, WHEEL_ID integer not null, KEY_CODE integer, EXPANDABLE bit, primary key (ID));
create table MAMMAL (ID integer not null, HAIR_COLOR varchar(255), primary key (ID));
create table MONITOR (DISPLAY_ID integer not null, BRAND varchar(255), primary key (DISPLAY_ID));
create table NO_ID_KEY (MY_KEY integer not null, NAME varchar(255), primary key (MY_KEY));
create table ORDERLINE (ID integer not null, NAME varchar(255), primary key (ID));
create table ORGANIZATION (ID integer not null, DISCRIMINATOR varchar(255) not null, NAME varchar(255), CEO varchar(255), AGENCY_BUDGET integer, primary key (ID));
create table PARENT (ID integer not null, NAME varchar(255), primary key (ID));
create table PASSANGER (ID integer not null, NAME varchar(255), primary key (ID));
create table PAYMENT (ID integer not null, AMOUNT integer, primary key (ID));
create table PENDANT (ID integer not null, SHAPE varchar(255), primary key (ID));
create table PERSON (ID integer not null, NAME varchar(255), ADDRESS_ID integer, primary key (ID), unique (ADDRESS_ID));
create table PRIVATE_TEACHER (TEACHER_ID integer not null, YEARS_EXPERIENCE integer, primary key (TEACHER_ID));
create table PRODUCT (ID integer not null, NAME varchar(255), ORDERLINE_ID integer, primary key (ID), unique (ORDERLINE_ID));
create table PROFESSOR (ID integer not null, NAME varchar(255), primary key (ID));
create table PROJECT (ID integer not null, NAME varchar(255), primary key (ID));
create table PUPIL (ID integer not null, NAME varchar(255), TEACHER_ID integer, primary key (ID));
create table RESTAURANT (ID integer not null, NAME varchar(255), primary key (ID));
create table SALTWATER_FISH_TANK (ID integer not null, PROTEIN_SKIMMER_MODEL varchar(255), NUM_GALLONS integer, SHAPE varchar(255), primary key (ID));
create table SALTWATER_FISH_TANK_SUBSTRATE (SALTWATER_FISH_TANK_ID integer not null, SUBSTRATE_ID integer not null, primary key (SALTWATER_FISH_TANK_ID, SUBSTRATE_ID), unique (SUBSTRATE_ID));
create table SHIRT (ID integer not null, STYLE varchar(255), primary key (ID));
create table SHIRT_BUTTON (SHIRT_ID integer not null, BUTTON_ID integer not null, primary key (SHIRT_ID, BUTTON_ID), unique (BUTTON_ID));
create table SHOES (ID integer not null, DISCRIMINATOR varchar(255) not null, COLOR varchar(255), SPORTS_TYPE varchar(255), DESIGNER_ID integer not null, primary key (ID));
create table SONG (ID integer not null, TITLE varchar(255), primary key (ID));
create table STRING_KEY (ID varchar(255) not null, NAME varchar(255), primary key (ID));
create table STRING_PRIMITIVE_KEY (ID varchar(255) not null, NAME varchar(255), primary key (ID));
create table STUDENT (ID integer not null, NAME varchar(255), primary key (ID));
create table SUBSTRATE (ID integer not null, NAME varchar(255), primary key (ID));
create table SUIT (ID integer not null, NAME varchar(255), DECK_ID integer not null, primary key (ID));
create table TANK_ACCESSORY (ID integer not null, NAME varchar(255), primary key (ID));
create table TANK_TANK_ACCESSORY (TANK_ID integer not null, TANK_ACCESSORY_ID integer not null, TANK_DISCRIMINATOR varchar(255));
create table TEACHER (ID integer not null, NAME varchar(255), primary key (ID));
create table TENURED_PROFESSOR (PROFESSOR_ID integer not null, TENURED_YEAR integer, primary key (PROFESSOR_ID));
create table UNDERGRADUATE_STUDENT (STUDENT_ID integer not null, primary key (STUDENT_ID));
create table UTENSIL (ID integer not null, NAME varchar(255), primary key (ID));
create table WHEEL (ID integer not null, RADIUS integer, primary key (ID));
alter table ALBUM_SONG add constraint FKEC3CB90581B87C90 foreign key (ALBUM_ID) references ALBUM;
alter table ALBUM_SONG add constraint FKEC3CB905EB7309A4 foreign key (SONG_ID) references SONG;
alter table ALL_DATA_TYPE_STRING_COLL add constraint FKF282088C4BF51B40 foreign key (ALL_DATA_TYPE_ID) references ALL_DATA_TYPE;
alter table ASSISTANT add constraint FKFB5182BE85D03B3B foreign key (PROFESSOR_ID) references PROFESSOR;
alter table ASSISTANT_PROFESSOR add constraint FK7FCA8E0E85D03B3B foreign key (PROFESSOR_ID) references PROFESSOR;
alter table ASSOCIATE_PROFESSOR add constraint FKEBBADA4E85D03B3B foreign key (PROFESSOR_ID) references PROFESSOR;
alter table AUTHOR_BOOK add constraint FKAC90951D11B08037 foreign key (AUTHOR_ID) references AUTHOR;
alter table AUTHOR_BOOK add constraint FKAC90951DC52E8EB7 foreign key (BOOK_ID) references BOOK;
alter table BAG_HANDLE add constraint FK8FC82A5FCEA84F85 foreign key (BAG_ID) references BAG;
alter table BAG_HANDLE add constraint FK8FC82A5FF35A2E0F foreign key (HANDLE_ID) references HANDLE;
alter table BRIDE_FATHER_IN_LAW add constraint FKBF51C6660B31E4 foreign key (BRIDE_ID) references BRIDE;
alter table BRIDE_FATHER_IN_LAW add constraint FKBF51C66CCF145D9 foreign key (IN_LAW_ID) references IN_LAW;
alter table BRIDE_MOTHER_IN_LAW add constraint FKFD41551FCCF145D9 foreign key (IN_LAW_ID) references IN_LAW;
alter table BRIDE_MOTHER_IN_LAW add constraint FKFD41551F3160483 foreign key (BRIDE_D) references BRIDE;
alter table CARD add constraint FK1F731031FBD7EF foreign key (SUIT_ID) references SUIT;
alter table CASH add constraint FK1F7333C2A7FD6D foreign key (PAYMENT_ID) references PAYMENT;
alter table CHAIN_PENDANT add constraint FKC8C94BDE7F591DB2 foreign key (CHAIN_ID) references CHAIN;
alter table CHAIN_PENDANT add constraint FKC8C94BDE8C56A5D2 foreign key (PENDANT_ID) references PENDANT;
alter table CHEF add constraint FK1F8BC698E6C48E foreign key (RESTAURANT_ID) references RESTAURANT;
alter table CHILD add constraint FK3D1FCFCA78EABE9 foreign key (MOTHER_ID) references PARENT;
alter table CHILD add constraint FK3D1FCFCEB5F2EB0 foreign key (FATHER_ID) references PARENT;
alter table CREDIT add constraint FK76F89EF9C2A7FD6D foreign key (PAYMENT_ID) references PAYMENT;
alter table CREDIT add constraint FK76F89EF9689593A7 foreign key (BANK_ID) references BANK;
alter table CRT_MONITOR add constraint FKDEE160C0196EE11C foreign key (MONITOR_ID) references MONITOR;
alter table DESSERT_UTENSIL add constraint FK4A0B93F5B3B2C9F5 foreign key (DESSERT_ID) references DESSERT;
alter table DESSERT_UTENSIL add constraint FK4A0B93F524333AC3 foreign key (UTENSIL_ID) references UTENSIL;
alter table ELEMENT add constraint FKC7AEAADCFE34B82A foreign key (PARENT_ELEMENT_ID) references ELEMENT;
alter table EMPLOYEE_PROJECT add constraint FKCE01C668422BA5BC foreign key (EMPLOYEE_ID) references EMPLOYEE;
alter table EMPLOYEE_PROJECT add constraint FKCE01C668D110B418 foreign key (PROJECT_ID) references PROJECT;
alter table FISH add constraint FK20EE582F7DE34C foreign key (TANK_ID) references SALTWATER_FISH_TANK;
alter table FISH add constraint FK20EE58ADE8D522 foreign key (TANK_ID) references FRESHWATER_FISH_TANK;
alter table FLIGHT_PASSANGER add constraint FK36CAD672729AF81 foreign key (FLIGHT_ID) references FLIGHT;
alter table FLIGHT_PASSANGER add constraint FK36CAD67432BA4D3 foreign key (PASSANGER_ID) references PASSANGER;
alter table GRADUATE_STUDENT add constraint FKCDCC8727904FA5F6 foreign key (STUDENT_ID) references STUDENT;
alter table GRAPHIC_CALCULATOR add constraint FK5CA0E0D9380BE9AC foreign key (CALCULATOR_ID) references CALCULATOR;
alter table HAND_CARD add constraint FKAAF560E0CA3044AF foreign key (HAND_ID) references HAND;
alter table HAND_CARD add constraint FKAAF560E0C1E7350F foreign key (CARD_ID) references CARD;
alter table HARD_DRIVE add constraint FK53512116252B1531 foreign key (COMPUTER_ID) references COMPUTER;
alter table HUMAN add constraint FK41E690D4AEB8790 foreign key (MAMMAL_ID) references MAMMAL;
alter table LATCH_KEY add constraint FK368069A481259D82 foreign key (KEYCHAIN_ID) references KEYCHAIN;
alter table LCD_MONITOR add constraint FK865718A8196EE11C foreign key (MONITOR_ID) references MONITOR;
alter table LUGGAGE add constraint FK496F4C16485FE8B5 foreign key (WHEEL_ID) references WHEEL;
alter table MONITOR add constraint FK747C493A8E7C481C foreign key (DISPLAY_ID) references DISPLAY;
alter table PERSON add constraint FK8C768F552E0F2091 foreign key (ADDRESS_ID) references ADDRESS;
alter table PRIVATE_TEACHER add constraint FK54CF9CE6406FC5A8 foreign key (TEACHER_ID) references TEACHER;
alter table PRODUCT add constraint FK185958CFD8F5D084 foreign key (ORDERLINE_ID) references ORDERLINE;
alter table PUPIL add constraint FK48F314E406FC5A8 foreign key (TEACHER_ID) references TEACHER;
alter table SALTWATER_FISH_TANK_SUBSTRATE add constraint FKF5625DB5A62A2163 foreign key (SALTWATER_FISH_TANK_ID) references SALTWATER_FISH_TANK;
alter table SALTWATER_FISH_TANK_SUBSTRATE add constraint FKF5625DB514F404D3 foreign key (SUBSTRATE_ID) references SUBSTRATE;
alter table SHIRT_BUTTON add constraint FKB28F85BBF7949550 foreign key (BUTTON_ID) references BUTTON;
alter table SHIRT_BUTTON add constraint FKB28F85BBD9B4EA64 foreign key (SHIRT_ID) references SHIRT;
alter table SHOES add constraint FK4B38AC85DD3FA8D foreign key (DESIGNER_ID) references DESIGNER;
alter table SUIT add constraint FK27030DFCD1226F foreign key (DECK_ID) references DECK;
alter table TANK_TANK_ACCESSORY add constraint FKD95079D22F7DE34C foreign key (TANK_ID) references SALTWATER_FISH_TANK;
alter table TANK_TANK_ACCESSORY add constraint FKD95079D2ADE8D522 foreign key (TANK_ID) references FRESHWATER_FISH_TANK;
alter table TANK_TANK_ACCESSORY add constraint FKD95079D27022CE1E foreign key (TANK_ACCESSORY_ID) references TANK_ACCESSORY;
alter table TENURED_PROFESSOR add constraint FKBA5BFB0985D03B3B foreign key (PROFESSOR_ID) references PROFESSOR;
alter table UNDERGRADUATE_STUDENT add constraint FK2E261DF904FA5F6 foreign key (STUDENT_ID) references STUDENT;
create table hi_value ( hi_value2 integer );
insert into hi_value values ( 0 );
