alter table ALBUM_SONG drop foreign key FKEC3CB90581B87C90;
alter table ALBUM_SONG drop foreign key FKEC3CB905EB7309A4;
alter table ALL_DATA_TYPE_STRING_COLL drop foreign key FKF282088C4BF51B40;
alter table ASSISTANT drop foreign key FKFB5182BE85D03B3B;
alter table ASSISTANT_PROFESSOR drop foreign key FK7FCA8E0E85D03B3B;
alter table ASSOCIATE_PROFESSOR drop foreign key FKEBBADA4E85D03B3B;
alter table AUTHOR_BOOK drop foreign key FKAC90951D11B08037;
alter table AUTHOR_BOOK drop foreign key FKAC90951DC52E8EB7;
alter table BAG_HANDLE drop foreign key FK8FC82A5FCEA84F85;
alter table BAG_HANDLE drop foreign key FK8FC82A5FF35A2E0F;
alter table BRIDE_FATHER_IN_LAW drop foreign key FKBF51C6660B31E4;
alter table BRIDE_FATHER_IN_LAW drop foreign key FKBF51C66CCF145D9;
alter table BRIDE_MOTHER_IN_LAW drop foreign key FKFD41551FCCF145D9;
alter table BRIDE_MOTHER_IN_LAW drop foreign key FKFD41551F3160483;
alter table CARD drop foreign key FK1F731031FBD7EF;
alter table CASH drop foreign key FK1F7333C2A7FD6D;
alter table CHAIN_PENDANT drop foreign key FKC8C94BDE7F591DB2;
alter table CHAIN_PENDANT drop foreign key FKC8C94BDE8C56A5D2;
alter table CHEF drop foreign key FK1F8BC698E6C48E;
alter table CHILD drop foreign key FK3D1FCFCA78EABE9;
alter table CHILD drop foreign key FK3D1FCFCEB5F2EB0;
alter table CREDIT drop foreign key FK76F89EF9C2A7FD6D;
alter table CREDIT drop foreign key FK76F89EF9689593A7;
alter table CRT_MONITOR drop foreign key FKDEE160C0196EE11C;
alter table DESSERT_UTENSIL drop foreign key FK4A0B93F5B3B2C9F5;
alter table DESSERT_UTENSIL drop foreign key FK4A0B93F524333AC3;
alter table ELEMENT drop foreign key FKC7AEAADCFE34B82A;
alter table EMPLOYEE_PROJECT drop foreign key FKCE01C668422BA5BC;
alter table EMPLOYEE_PROJECT drop foreign key FKCE01C668D110B418;
alter table FISH drop foreign key FK20EE582F7DE34C;
alter table FISH drop foreign key FK20EE58ADE8D522;
alter table FLIGHT_PASSANGER drop foreign key FK36CAD672729AF81;
alter table FLIGHT_PASSANGER drop foreign key FK36CAD67432BA4D3;
alter table GRADUATE_STUDENT drop foreign key FKCDCC8727904FA5F6;
alter table GRAPHIC_CALCULATOR drop foreign key FK5CA0E0D9380BE9AC;
alter table HAND_CARD drop foreign key FKAAF560E0CA3044AF;
alter table HAND_CARD drop foreign key FKAAF560E0C1E7350F;
alter table HARD_DRIVE drop foreign key FK53512116252B1531;
alter table HUMAN drop foreign key FK41E690D4AEB8790;
alter table LATCH_KEY drop foreign key FK368069A481259D82;
alter table LCD_MONITOR drop foreign key FK865718A8196EE11C;
alter table LUGGAGE drop foreign key FK496F4C16485FE8B5;
alter table MONITOR drop foreign key FK747C493A8E7C481C;
alter table PERSON drop foreign key FK8C768F552E0F2091;
alter table PRIVATE_TEACHER drop foreign key FK54CF9CE6406FC5A8;
alter table PRODUCT drop foreign key FK185958CFD8F5D084;
alter table PUPIL drop foreign key FK48F314E406FC5A8;
alter table SALTWATER_FISH_TANK_SUBSTRATE drop foreign key FKF5625DB5A62A2163;
alter table SALTWATER_FISH_TANK_SUBSTRATE drop foreign key FKF5625DB514F404D3;
alter table SHIRT_BUTTON drop foreign key FKB28F85BBF7949550;
alter table SHIRT_BUTTON drop foreign key FKB28F85BBD9B4EA64;
alter table SHOES drop foreign key FK4B38AC85DD3FA8D;
alter table SUIT drop foreign key FK27030DFCD1226F;
alter table TANK_TANK_ACCESSORY drop foreign key FKD95079D22F7DE34C;
alter table TANK_TANK_ACCESSORY drop foreign key FKD95079D2ADE8D522;
alter table TANK_TANK_ACCESSORY drop foreign key FKD95079D27022CE1E;
alter table TENURED_PROFESSOR drop foreign key FKBA5BFB0985D03B3B;
alter table UNDERGRADUATE_STUDENT drop foreign key FK2E261DF904FA5F6;
drop table if exists ADDRESS;
drop table if exists ALBUM;
drop table if exists ALBUM_SONG;
drop table if exists ALL_DATA_TYPE;
drop table if exists ALL_DATA_TYPE_STRING_COLL;
drop table if exists ASSISTANT;
drop table if exists ASSISTANT_PROFESSOR;
drop table if exists ASSOCIATE_PROFESSOR;
drop table if exists AUTHOR;
drop table if exists AUTHOR_BOOK;
drop table if exists BAG;
drop table if exists BAG_HANDLE;
drop table if exists BANK;
drop table if exists BOOK;
drop table if exists BRIDE;
drop table if exists BRIDE_FATHER_IN_LAW;
drop table if exists BRIDE_MOTHER_IN_LAW;
drop table if exists BUTTON;
drop table if exists CALCULATOR;
drop table if exists CARD;
drop table if exists CASH;
drop table if exists CHAIN;
drop table if exists CHAIN_PENDANT;
drop table if exists CHARACTER_KEY;
drop table if exists CHARACTER_PRIMITIVE_KEY;
drop table if exists CHEF;
drop table if exists CHILD;
drop table if exists COMPUTER;
drop table if exists CREDIT;
drop table if exists CRT_MONITOR;
drop table if exists CURRENCY;
drop table if exists DECK;
drop table if exists DESIGNER;
drop table if exists DESSERT;
drop table if exists DESSERT_UTENSIL;
drop table if exists DISPLAY;
drop table if exists DOG;
drop table if exists DOUBLE_KEY;
drop table if exists DOUBLE_PRIMITIVE_KEY;
drop table if exists ELEMENT;
drop table if exists EMPLOYEE;
drop table if exists EMPLOYEE_PROJECT;
drop table if exists FISH;
drop table if exists FLIGHT;
drop table if exists FLIGHT_PASSANGER;
drop table if exists FLOAT_KEY;
drop table if exists FLOAT_PRIMITIVE_KEY;
drop table if exists FRESHWATER_FISH_TANK;
drop table if exists GOVERMENT;
drop table if exists GRADUATE_STUDENT;
drop table if exists GRAPHIC_CALCULATOR;
drop table if exists HAND;
drop table if exists HANDLE;
drop table if exists HAND_CARD;
drop table if exists HARD_DRIVE;
drop table if exists HUMAN;
drop table if exists INTEGER_KEY;
drop table if exists INTEGER_PRIMITIVE_KEY;
drop table if exists IN_LAW;
drop table if exists KEYCHAIN;
drop table if exists LATCH_KEY;
drop table if exists LCD_MONITOR;
drop table if exists LONG_KEY;
drop table if exists LONG_PRIMITIVE_KEY;
drop table if exists LUGGAGE;
drop table if exists MAMMAL;
drop table if exists MONITOR;
drop table if exists NO_ID_KEY;
drop table if exists ORDERLINE;
drop table if exists ORGANIZATION;
drop table if exists PARENT;
drop table if exists PASSANGER;
drop table if exists PAYMENT;
drop table if exists PENDANT;
drop table if exists PERSON;
drop table if exists PRIVATE_TEACHER;
drop table if exists PRODUCT;
drop table if exists PROFESSOR;
drop table if exists PROJECT;
drop table if exists PUPIL;
drop table if exists RESTAURANT;
drop table if exists SALTWATER_FISH_TANK;
drop table if exists SALTWATER_FISH_TANK_SUBSTRATE;
drop table if exists SHIRT;
drop table if exists SHIRT_BUTTON;
drop table if exists SHOES;
drop table if exists SONG;
drop table if exists STRING_KEY;
drop table if exists STRING_PRIMITIVE_KEY;
drop table if exists STUDENT;
drop table if exists SUBSTRATE;
drop table if exists SUIT;
drop table if exists TANK_ACCESSORY;
drop table if exists TANK_TANK_ACCESSORY;
drop table if exists TEACHER;
drop table if exists TENURED_PROFESSOR;
drop table if exists UNDERGRADUATE_STUDENT;
drop table if exists UTENSIL;
drop table if exists WHEEL;
drop table if exists hi_value;
